web: gunicorn --chdir socialpullybac/video_downloader video_downloader.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300
release: python socialpullybac/video_downloader/manage.py migrate && python socialpullybac/video_downloader/manage.py collectstatic --noinput
